### PR TITLE
Adding Kin Markets and Mint Address

### PR DESCRIPTION
**Pull request by myyellowshoe**

### CODE REVIEW

**Comment by nathanielparke** [comment]
Hi @myyellowshoe, Thanks for the PR! Looks like the markets specified have large price tick sizes relative to the current market price of KIN. I went ahead and re-listed these markets with more reasonable parameters. I will merge those markets shortly.

**Comment by nathanielparke** [comment]
Additionally, I believe there is a typo in the coin mint for KIN as the specified mint is not valid base58

**Comment by nathanielparke** [comment]
Additionally I believe there is a typo in the coin mint as the one provided is the incorrect size.

**Comment by nathanielparke** [comment]
closing this in favor of #49

**Comment by myyellowshoe** [comment]
Thanks for the feedback @nathanielparke. Still learning the ropes of markets and such on serum :)
Thanks for fixing the issues with those markets.

Ugh yeah looks like I had a t on the end for some reason. Appreciate you catching that.

**Pull request closed without merging**
