### PR TITLE
Add KIN markets

### PR DESCRIPTION
**Pull request by nathanielparke**

### CODE REVIEW

**Comment by myyellowshoe** [comment]
Is there a reason you added USDC/USDT markets but left out SRM/SOL markets?

**Comment by nathanielparke** [comment]
Nope! Happy to include those as well with similar market parameters to the stablecoin markets

**Comment by myyellowshoe** [comment]
Oh sweet. Gracias :)

**Comment by myyellowshoe** [comment]
howdy! Just following up.  Are you going to take care of that or would you like me to get those markets together?

**Pull request merged**
